// <auto-generated />
using System;
using A_Simple_Hr_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace A_Simple_Hr_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251021084813_AddShiftTable")]
    partial class AddShiftTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Company", b =>
                {
                    b.Property<Guid>("ComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Basic")
                        .HasColumnType("numeric");

                    b.Property<string>("ComName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Hrent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Medical")
                        .HasColumnType("numeric");

                    b.HasKey("ComId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Department", b =>
                {
                    b.Property<Guid>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeptId");

                    b.HasIndex("ComId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Designation", b =>
                {
                    b.Property<Guid>("DesigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComId")
                        .HasColumnType("uuid");

                    b.Property<string>("DesigName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DesigId");

                    b.HasIndex("ComId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("In")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Late")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Out")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShiftId");

                    b.HasIndex("ComId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Department", b =>
                {
                    b.HasOne("A_Simple_Hr_Management_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Designation", b =>
                {
                    b.HasOne("A_Simple_Hr_Management_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Shift", b =>
                {
                    b.HasOne("A_Simple_Hr_Management_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
