// <auto-generated />
using System;
using A_Simple_Hr_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace A_Simple_Hr_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022053637_AddAttendanceTable")]
    partial class AddAttendanceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ComId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("InTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("OutTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("dtDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ComId");

                    b.HasIndex("EmpId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Company", b =>
                {
                    b.Property<Guid>("ComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Basic")
                        .HasColumnType("numeric");

                    b.Property<string>("ComName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Hrent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Medical")
                        .HasColumnType("numeric");

                    b.HasKey("ComId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Department", b =>
                {
                    b.Property<Guid>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeptId");

                    b.HasIndex("ComId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Designation", b =>
                {
                    b.Property<Guid>("DesigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComId")
                        .HasColumnType("uuid");

                    b.Property<string>("DesigName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DesigId");

                    b.HasIndex("ComId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Employee", b =>
                {
                    b.Property<Guid>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Basic")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ComId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DesigId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Gross")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("HRent")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Medical")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Others")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("dtJoin")
                        .HasColumnType("date");

                    b.HasKey("EmpId");

                    b.HasIndex("ComId");

                    b.HasIndex("DeptId");

                    b.HasIndex("DesigId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("In")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Late")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Out")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShiftId");

                    b.HasIndex("ComId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Attendance", b =>
                {
                    b.HasOne("A_Simple_Hr_Management_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Simple_Hr_Management_System.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Department", b =>
                {
                    b.HasOne("A_Simple_Hr_Management_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Designation", b =>
                {
                    b.HasOne("A_Simple_Hr_Management_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Employee", b =>
                {
                    b.HasOne("A_Simple_Hr_Management_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Simple_Hr_Management_System.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Simple_Hr_Management_System.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Simple_Hr_Management_System.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("A_Simple_Hr_Management_System.Models.Shift", b =>
                {
                    b.HasOne("A_Simple_Hr_Management_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
